### ISSUE TITLE
Playground broken

### ISSUE THREAD

**Issue by mibitzi** [gopherjs/gopherjs.github.io#24]
Running the default/example code in the playground gives
```
 SyntaxError: Unexpected token [
    at eval (native)
    at $packages.github.com/gopherjs/gopherjs.github.io/playground.e.NewController.$f (http://www.gopherjs.org/playground/playground.js:73:9130)
    at k.v.$externalizeWrapper [as run] (http://www.gopherjs.org/playground/playground.js:4:33875)
    at bb.functionCall (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:175:190)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:192:165
    at k.$get.k.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:112:32)
    at k.$get.k.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:112:310)
    at HTMLInputElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:192:147)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:31:225
    at Array.forEach (native)
    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:7:280)
    at HTMLInputElement.c (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:31:207)angular.js:9937 (anonymous function)angular.js:7283 $getangular.js:12656 $get.k.$applyangular.js:18881 (anonymous function)angular.js:2816 (anonymous function)angular.js:320 qangular.js:2815 c
```

**Comment by neelance** [comment]
Oops, seems like I uploaded a broken version. Thanks for reporting! I've fixed it now.
